#!/usr/bin/env bash
# Bash script that pings accepting an IP as an argument and pings it 5 times

if [ $# -ne 1 ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

ping -c 5 "$1"