#!/usr/bin/env bash
# Script that that configures an Ubuntu server with the below requirements:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8.

# Backup the current /etc/hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Add new entries to hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts